INT-2420 Update documentation for adding satisfaction.answered event
iadvize/documentation pull request #187
Opened 2021-03-04 15:25 UTC by maylencita

#### What's this PR purpose?
> Ticket link [INT-2420](https://iadvize.atlassian.net/browse/INT-2420)

#### Description

#### PR Dependencies

2021-03-04 15:52 UTC, maylencita commented on docs/webhooks.md
> +<!-- Should we remove this section ? -->
@eroak  ?

2021-03-04 15:59 UTC, sdemonti requested changes

2021-03-04 15:59 UTC, sdemonti commented on docs/webhooks.md
> +    "eventType": "user.updated",
```suggestion
    "eventType": "satisfaction.answered",
```

2021-03-04 15:59 UTC, sdemonti commented on docs/webhooks.md
> +    "eventType": "user.updated",
```suggestion
    "eventType": "satisfaction.answered",
```

2021-03-04 15:59 UTC, sdemonti commented on docs/webhooks.md
> +    "eventType": "user.updated",
```suggestion
    "eventType": "satisfaction.answered",
```

2021-03-05 15:10 UTC, jcare44 approved these changes

2021-03-08 07:43 UTC, sdemonti requested changes

2021-03-08 07:43 UTC, sdemonti commented on docs/webhooks.md
> +    "clientId": 1,
il manque aussi le projectId

2021-03-08 07:45 UTC, sdemonti requested changes

2021-03-08 07:45 UTC, sdemonti commented on docs/webhooks.md
> +    "userId": 1,
le userId est en trop

2021-03-09 08:11 UTC, sdemonti approved these changes

2021-03-11 13:24 UTC, merged