doc/TPC-1320-split-mobile-sdk-doc-by-platform
iadvize/documentation pull request #249
Opened 2022-12-30 13:37 UTC by Judas

#### What's this PR purpose?
> [Split dev-platform documentation for each available platform](https://iadvize.atlassian.net/browse/TPC-1320)

#### Description
This PR splits the Mobile SDK documentation into 4 sections, one per mobile platform (Android, iOS, ReactNative, Flutter)

2022-12-30 14:26 UTC, EtienneRd reviewed
The satisfaction survey gif does not show the NPS fix

2023-01-03 10:29 UTC, alexduf requested changes

2023-01-03 10:29 UTC, alexduf commented on docs/mobile-sdk.md
> +Add the iAdvize Messenger SDK dependency inside your module-level Gradle build file (replace `x.y.z` by the SDK latest version available):
```suggestion
Add the iAdvize Messenger SDK dependency inside your module-level Gradle build file (replace `x.y.z` by the latest SDK version available):
```

2023-01-03 10:29 UTC, alexduf commented on docs/mobile-sdk.md
> +Before activating the SDK, you will need to provide a reference to your application object and initiate the SDK with it.
```suggestion
Before activating the SDK, you will need to provide a reference to your application object and initialize the SDK with it.
```

2023-01-03 10:29 UTC, alexduf commented on docs/mobile-sdk.md
> +After that you can activate the SDK using the `activate` function with your `projectId` (see the [Prerequisites](#⚙️-prerequisites) section above to get that identifier). You have access to callbacks
```suggestion
Afterwards you can activate the SDK using the `activate` function with your `projectId` (see the [Prerequisites](#⚙️-prerequisites) section above to get that identifier). You have access to callbacks in order to know if the SDK has been successfully activated. In the case of an SDK activation failure the callback will give you the reason of the failure and you may want to retry later:
```

2023-01-03 10:29 UTC, alexduf commented on docs/mobile-sdk.md
> +> *⚠️ After you activate a rule and it succeeds (by displaying the button), those conditions are checked every 30 seconds to verify that the button should still be displayed or not. At the first fail
```suggestion
> *⚠️ After you activate a rule and it succeeds (by displaying the button), those conditions are checked every 30 seconds to verify that the button should still be displayed or not. Upon first failure from this periodic check, the button is hidden and the SDK stops verifying the conditions. It means that if the rule cannot be triggered (after the first call, or after any successive check), you will have to call the `activateTargetingRule` (or `registerUserNavigation`) method again in order to restart the engagement process.*
```

2023-01-03 10:29 UTC, alexduf commented on docs/mobile-sdk.md
> +Please also be sure to initiate the SDK during the unit tests setup (see the [Setting up the SDK](#⚙️-setting-up-the-sdk) section above).
```suggestion
Please also be sure to initialize the SDK during the unit tests setup (see the [Setting up the SDK](#⚙️-setting-up-the-sdk) section above).
```

2023-01-03 10:30 UTC, alexduf approved these changes

2023-01-03 13:04 UTC, merged